name: cancellable
description: This package provides a capability for cancellation.
version: 1.1.6
homepage: https://github.com/aymtools/cancellable
topics:
  - cancel
  - cancelable
  - cancel-token
  - cancellation

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  weak_collections: ^1.1.0