name: cancellable
description: This package provides a capability for cancellation.This feature allows termination or revocation of operations through a certain mechanism during task execution.
version: 2.3.0
homepage: https://github.com/aymtools/cancellable

topics:
  - cancel
  - cancelable
  - cancel-token
  - cancellation
  - dispose

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  weak_collections: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
