name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*.*'

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: aymtools/flutter-ci/.github/workflows/dart-publish.yml@v6